name: NPM Version Patch

on:
  push:
    branches:
      - dev

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Bump package version (patch)
      run: npm version patch --no-git-tag-version

    - name: Commit and push updated package.json
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add package.json
        git commit -m "Bump package version (patch)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}