name: NPM Version Patch

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Bump package version (patch)
      run: npm version patch --no-git-tag-version

    - name: Commit and push to a new branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b patch-bump-${{ github.run_id }}
        git add package.json
        git diff --cached --quiet || git commit -m "Bump package version (patch)"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push -u origin patch-bump-${{ github.run_id }}

    - name: Create Pull Request
      if: ${{ success() }}
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Bump package version (patch)"
        base: dev
        branch: patch-bump-${{ github.run_id }}
        body: "This PR bumps the package version (patch) and should be merged back into the `dev` branch."